### ISSUE TITLE
Drop support for Android 4.4

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-android#169]
Remove Crosswalk once and for all. Consider implications if phone's webview is too old.

**Comment by latin-panda** [comment]
This is ready for AT in these PRs:

[CHT-Android PR](https://github.com/medic/cht-android/pull/236)
[CHT-Docs PR](https://github.com/medic/cht-docs/pull/588)

It's a big change, so it'd be good to include several devices during AT. Some every old devices will need to upgrade their WebView version, for example Android 5 phones can have WebView v35 from factory which is too old and needs upgrade. 

Another suggestion is to ensure that branded versions are building correctly.

**Comment by ngaruko** [comment]
Taking notes here as we go:

1. Some the old phones might have no webview installed (happens on a `TECNO TECNO-J5 `with `Android 5.1`)...and attempts to install the app throw errors:
```
01/07 12:31:59: Launching 'cht-android' on TECNO TECNO-J5.
Installation did not succeed.
The application could not be installed.

List of apks:
[0] '/Users/bede/Medic/cht-android/build/outputs/apk/unbranded/debug/cht-android-SNAPSHOT-unbranded-armeabi-v7a-debug.apk'
Installation failed due to: ''pm install-create -r -t -S 2174757' returns error 'Unknown failure: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String android.os.SystemProperties.native_get(java.lang.String) (tried Java_android_os_SystemProperties_native_1get and Java_android_os_SystemProperties_native_1get__Ljava_lang_String_2)
at android.os.SystemProperties.native_get(Native Method)
at android.os.SystemProperties.get(SystemProperties.java:52)
at android.os.Environment.getCanonicalPathOrNull(Environment.java:832)
at android.os.Environment.<clinit>(Environment.java:83)
at android.os.Environment.getLegacyExternalStorageDirectory(Environment.java:419)
at android.os.Debug.<clinit>(Debug.java:101)
at android.ddm.DdmHandleHello.handleHELO(DdmHandleHello.java:164)
at android.ddm.DdmHandleHello.handleChunk(DdmHandleHello.java:91)
at org.apache.harmony.dalvik.ddmc.DdmServer.dispatch(DdmServer.java:171)
java.lang.UnsatisfiedLinkError: android.os.Debug
at android.ddm.DdmHandleHello.handleFEAT(DdmHandleHello.java:176)
at android.ddm.DdmHandleHello.handleChunk(DdmHandleHello.java:93)
at org.apache.harmony.dalvik.ddmc.DdmServer.dispatch(DdmServer.java:171)
java.lang.UnsatisfiedLinkError: android.os.Debug
at android.ddm.DdmHandleProfiling.handleMPRQ(DdmHandleProfiling.java:187)
at android.ddm.DdmHandleProfiling.handleChunk(DdmHandleProfiling.java:88)
at org.apache.harmony.dalvik.ddmc.DdmServer.dispatch(DdmServer.java:171)''
Retry

```
2. Work around: installed webview from [Google Play](https://play.google.com/store/apps/details?id=com.google.android.webview) and voila. However, this, this might be an issue for projects migrating - so it has to be investigated further, well documented and properly communicated. Pining @derickl as a heads-up.
3. Wondering if on our end we could check first if WebView is installed and return a meaningfull error, at least for the interim. Thoughts @latin-panda ?

**Comment by ngaruko** [comment]
I uninstalled the existing version of webview (v39 on the phone) and installed the newest from Google Play and the app crashes on launch:
```
Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f07007e}
E/WebViewFactory: Failed to list WebView package libraries for loadNativeLibrary
    android.content.pm.PackageManager$NameNotFoundException: com.android.webview
        at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:286)
        at android.webkit.WebViewFactory.getWebViewNativeLibraryPaths(WebViewFactory.java:282)
        at android.webkit.WebViewFactory.loadNativeLibrary(WebViewFactory.java:397)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:103)
        at android.webkit.WebView.getFactory(WebView.java:2326)
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2321)
        at android.webkit.WebView.setOverScrollMode(WebView.java:2386)
        at android.view.View.<init>(View.java:3632)
        at android.view.View.<init>(View.java:3736)
        at android.view.ViewGroup.<init>(ViewGroup.java:524)
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
        at android.webkit.WebView.<init>(WebView.java:581)
        at android.webkit.WebView.<init>(WebView.java:526)
        at android.webkit.WebView.<init>(WebView.java:509)
        at android.webkit.WebView.<init>(WebView.java:496)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:421)
        at android.app.Activity.setContentView(Activity.java:2175)
        at org.medicmobile.webapp.mobile.EmbeddedBrowserActivity.onCreate(EmbeddedBrowserActivity.java:105)
        at android.app.Activity.performCreate(Activity.java:6092)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
        at android.app.ActivityThread.access$800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5631)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
E/WebViewFactory: Chromium WebView package does not exist
    android.content.pm.PackageManager$NameNotFoundException: com.android.webview
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:119)
        at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:146)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109)
        at android.webkit.WebView.getFactory(WebView.java:2326)
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2321)
        at android.webkit.WebView.setOverScrollMode(WebView.java:2386)
        at android.view.View.<init>(View.java:3632)
        at android.view.View.<init>(View.java:3736)
        at android.view.ViewGroup.<init>(ViewGroup.java:524)
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
        at android.webkit.WebView.<init>(WebView.java:581)
        at android.webkit.WebView.<init>(WebView.java:526)
        at android.webkit.WebView.<init>(WebView.java:509)
        at android.webkit.WebView.<init>(WebView.java:496)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:421)
        at android.app.Activity.setContentView(Activity.java:2175)
        at org.medicmobile.webapp.mobile.EmbeddedBrowserActivity.onCreate(EmbeddedBrowserActivity.java:105)
        at android.app.Activity.performCreate(Activity.java:6092)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
        at android.app.ActivityThread.access$800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5631)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.medicmobile.webapp.mobile.unbranded_test, PID: 30172
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.medicmobile.webapp.mobile.unbranded_test/org.medicmobile.webapp.mobile.EmbeddedBrowserActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class android.webkit.WebView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
        at android.app.ActivityThread.access$800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5631)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class android.webkit.WebView
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:421)
        at android.app.Activity.setContentView(Activity.java:2175)
        at org.medicmobile.webapp.mobile.EmbeddedBrowserActivity.onCreate(EmbeddedBrowserActivity.java:105)
        at android.app.Activity.performCreate(Activity.java:6092)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
        at android.app.ActivityThread.access$800(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5631) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:421) 
        at android.app.Activity.setContentView(Activity.java:2175) 
        at org.medicmobile.webapp.mobile.EmbeddedBrowserActivity.onCreate(EmbeddedBrowserActivity.java:105) 
        at android.app.Activity.performCreate(Activity.java:6092) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
        at android.app.ActivityThread.access$800(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5631) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
     Caused by: android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.android.webview
        at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:174)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109)
        at android.webkit.WebView.getFactory(WebView.java:2326)
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2321)
        at android.webkit.WebView.setOverScrollMode(WebView.java:2386)
        at android.view.View.<init>(View.java:3632)
        at android.view.View.<init>(View.java:3736)
        at android.view.ViewGroup.<init>(ViewGroup.java:524)
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
        at android.webkit.WebView.<init>(WebView.java:581)
        at android.webkit.WebView.<init>(WebView.java:526)
        at android.webkit.WebView.<init>(WebView.java:509)
        at android.webkit.WebView.<init>(WebView.java:496)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:421) 
        at android.app.Activity.setContentView(Activity.java:2175) 
        at org.medicmobile.webapp.mobile.EmbeddedBrowserActivity.onCreate(EmbeddedBrowserActivity.java:105) 
        at android.app.Activity.performCreate(Activity.java:6092) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
        at android.app.ActivityThread.access$800(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5631) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
     Caused by: android.content.pm.PackageManager$NameNotFoundException: com.android.webview
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:119)
        at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:146)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109) 
        at android.webkit.WebView.getFactory(WebView.java:2326) 
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2321) 
        at android.webkit.WebView.setOverScrollMode(WebView.java:2386) 
        at android.view.View.<init>(View.java:3632) 
        at android.view.View.<init>(View.java:3736) 
        at android.view.ViewGroup.<init>(ViewGroup.java:524) 
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55) 
        at android.webkit.WebView.<init>(WebView.java:581) 
        at android.webkit.WebView.<init>(WebView.java:526) 
        at android.webkit.WebView.<init>(WebView.java:509) 
        at android.webkit.WebView.<init>(WebView.java:496) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:421) 
        at android.app.Activity.setContentView(Activity.java:2175) 
        at org.medicmobile.webapp.mobile.EmbeddedBrowserActivity.onCreate(EmbeddedBrowserActivity.java:105) 
        at android.app.Activity.performCreate(Activity.java:6092) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
        at android.app.ActivityThread.access$800(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5631) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
I/Process: Sending signal. PID: 30172 SIG: 9

```

**Comment by latin-panda** [comment]
The next step is to research a way to set the android system to use by default the WebView from Playstore instead of the one from the System.

**Comment by craig-landry** [comment]
On the team call today some project survey data was mentioned for versions and usage. I'm linking that [Android 4.4 partner communication](https://docs.google.com/spreadsheets/d/1KGVfg8qsk6kiKoi69PYIW4rcWmTHGgkcQFrNv_WYbL0/edit#gid=0) here for others to easily reference.

**Comment by latin-panda** [comment]
Update:
The app is working in `Android 5.1 `that already has `WebView from PlayStore (gear icon)`, these phones are: 
- `Alcatel onetouch Pixi3 Android 5.1, WebView v95`
- `Sony Xperia Android 5.1, WebView v95`

Also verified and working in 
- `Huawei Android 9, WebView v74`
- `Nokia 8 Android 9, WebView v95`
- `Samsung S10+ Android 11, WebView v97` 

WebView from PlayStore (gear icon) originally in the following phone:
- `Moto X, Android 5.1`
- `HTC, Android 5.1`

None of the phones mentioned above has 2 WebViews apps at the same time, those don't have old WebView from System (planet icon) 

🧐 Currently I'm trying to get information from partners using techno phones to confirm if this is brand/model issue.

**Comment by latin-panda** [comment]
Update:
I've gotten the following feedback from some partners using Tecno phones:

- LG have moved out from `Tecno Android 5` and now they're using `Tecno Android 8 & 9`, still waiting to hear back about more detail on the phone's specs. 
- Muso is now using `Tecno Android 9`.
- Asia's projects ICM and NSSD are using `Android 9`.
- 👀 IH still hasn't answered to our questions - so waiting to hear back about their current Android version.

**Comment by ngaruko** [comment]
@latin-panda Since apparently no partner is using Tecno Android 5, I think it is safe to assume that this issue is not likely to occur in production... and considering how much research and engineering time has gone into this far, I would suggest we close it off. Considering that [Google separated WebView from the core OS with Android 5.0 Lollipop](https://www.androidpolice.com/2014/10/19/lollipop-feature-spotlight-webview-now-unbundled-android-free-auto-update-google-play/) over 7 years ago, there is a high chance that none is still using those devices.
Unless there is an objection from @medic/app-services-team or @medic/product-management  or....

**Comment by latin-panda** [comment]
@ngaruko is this good to merge? Can we move the ticket? 🤔 I was out in the last product meeting and no recordings

**Comment by ngaruko** [comment]
@latin-panda Yes. I made a call with the above rationale.

**Comment by latin-panda** [comment]
Thank you!
Merged into main branch.
